// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWW9yjyD6gx24ohrKUZkFaQGC4wuFsrLs',
    appId: '1:885526293102:android:4f2c7e31f57066090fd47f',
    messagingSenderId: '885526293102',
    projectId: 'cuwancerdas',
    storageBucket: 'cuwancerdas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1KWONZyq95_loNMEvTEmcKlzIJH8Hyy8',
    appId: '1:885526293102:ios:b4167a367b62b0fd0fd47f',
    messagingSenderId: '885526293102',
    projectId: 'cuwancerdas',
    storageBucket: 'cuwancerdas.appspot.com',
    androidClientId: '885526293102-3n47gdq3be1tls90f8gc80a7i1ril3hc.apps.googleusercontent.com',
    iosClientId: '885526293102-8u9g42pvr77i50psbaqjc1aa36r2e9os.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuancerdas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMXr1HX-YMn_XGHmgJ5ilK9-cjCMO0j8s',
    appId: '1:885526293102:web:7ac360d6b5f7e1220fd47f',
    messagingSenderId: '885526293102',
    projectId: 'cuwancerdas',
    authDomain: 'cuwancerdas.firebaseapp.com',
    storageBucket: 'cuwancerdas.appspot.com',
    measurementId: 'G-L18QZ3K4VG',
  );
}
